sudo: required
language: generic
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
install:
  - npm install
  - docker build -t rabbit_delimiter .
before_script:
  - docker run -d -p 5672:5672 -p 15672:15672 --name rabbit rabbit_delimiter
  - ./bin/wait-for-success curl -o /dev/null -sIf http://localhost:15672
script:
  - npm test
after_failure:
  - docker logs rabbit
