sudo: required
language: elixir
elixir:
  - 1.4.5
otp_release:
  - 19.3
  - 18.3
  - 17.5
services:
  - docker
install:
  - npm install
  - docker build -t rabbit_delimiter .
before_script:
  - docker run -d -e RABBITMQ_DEFAULT_USER=guest -e RABBITMQ_DEFAULT_PASS=guest -p 5672:5672 -p 15672:15672 rabbit_delimiter
  - ./bin/wait-for-success curl --output /dev/null --silent --head --fail http://localhost:15672
script:
  - npm test
